config/routes.rb
UsaToday::Application.routes.draw do
  mount Split::Dashboard, at: 'split'
  root :to => 'home#index'
  match 'news' => 'contact#news'
  match 'sports' => 'contact#sports'
  match 'life' => 'contact#life'
  match 'money' => 'contact#money'
  match 'tech' => 'contact#tech'
  match 'opinion' => 'contact#opinion'
  match 'stocks' => 'contact#stocks'
  match 'videos' => 'contact#videos'
  match 'elections' => 'contact#elections'
  match 'investigations' => 'contact#investigations'
  match 'contact' => 'contact#index'
  match 'contact/submit' => 'contact#submit'
  match 'prince' => 'contact#prince'
  match 'golden-state-warriors' => 'contact#dubs'
  match 'caterpillar' => 'contact#caterpillar'
  match 'wallstreet' => 'contact#wallstreet'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def news
    
  end

  def index
    if params["department"].present?
      finished("contact_us")
      render "submit"
    end
  end

  def submit

  end

  def sports
    
  end

  def life
    
  end

  def money
    
  end

  def tech
    
  end

  def stocks
    
  end

  def opinion
    
  end

  def videos
    
  end

  def elections
    
  end

  def investiongations
    
  end

  def prince
    
  end

  def dubs
    
  end

  def caterpillar
    
  end

  def wallstreet
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'active' : ''
    content_tag(:li, :class => class_name) do
      link_to link_text, link_path
    end
  end
end

app/views/contact/caterpillar.html.erb
<div class="content-description-page">
  <div class="content-description-image">
    <%= image_tag("/assets/sec_caterpillar.jpg") %>
  </div>
  <div class="content-description-content">
    <h4>Caterpillar cuts 2016 sales, earnings outlook, posts lower first-quarter profit</h4>
    <p>(Reuters) - Caterpillar Inc. (CAT.N) lowered its 2016 sales and earnings outlook and posted a lower first-quarter net profit on Friday as revenues declined in the company's construction, oil and gas, mining and rail business segments.</p>

    <p>The company said it expects 2016 sales in a range of $40 billion to $42 billion against a previously forecast $40 billion to $44 billion.</p>

    <p>Caterpillar now expects 2016 earnings per share at $3.00, or $3.70 per share excluding restructuring costs. The previous forecast was $3.50 per share, or $4.00 per share excluding restructuring costs.</p>

    <p>The world’s largest heavy machinery manufacturer reported a net income of $494 million, or 67 cents per share in the first quarter, down from a revised $1.70 billion, or $2.07 a share, a year ago. Analysts had expected earnings per share of 68 cents.</p>

    <p>Including restructuring costs, Caterpillar earned 46 cents per share, compared with a revised $2.03 a year earlier. Revenue fell to $9.46 billion from $12.7 billion a year ago.</p>

    <p>(Reporting by Meredith Davis; Editing by W Simon)</p>

    <p>The two teams never did anything to draw technical or flagrant fouls, but there was clearly increased physicality on both sides. We'll see if it leads to anything further before the series is up.</p>
  </div>
</div>

app/views/contact/dubs.html.erb
<div class="content-description-page">
  <div class="content-description-image">
    <%= image_tag("/assets/sec_dubbs.jpg") %>
  </div>
  <div class="content-description-content">
    <h4>Warriors vs. Rockets, 2016 NBA playoff results: 3 things from Houston's last-second 97-96 win</h4>
    <p>For the second-straight game, the Golden State Warriors played the Houston Rockets without Stephen Curry. Somehow, despite several miscues in the final minute, the Rockets barely snuck out a win on their home floor, with their 97-96 victory reducing the series to a 2-1 Warriors lead.</p>

    <p>With 12 seconds left up one, the Rockets inbounded the ball to no one, leading the Warriors go straight down the court for an easy Ian Clark layup. Harden answered right back with a stepback jumper to put Houston back up by a point, and Draymond Green lost the ball off his foot to all but end the game.</p>

    <p>Actually taking advantage of Curry's absence, it was Houston who took over early, leading 31-18 after the first quarter and still holding a seven-point advantage at halftime. The Rockets reached double digits in the third quarter, but back came Golden State. After a Donatas Motiejunas triple with 4:39 to play put Houston up 91-83, it looked like Houston might survive. But once again, the Warriors refused to die even missing their best player.</p>

    <p>Clark was a huge factor off the bench, nailing the go-ahead floater that put Golden State ahead for the first time since the game was 2-0. Clark finished with 11 points and five assists, hitting all four of his field goals in the fourth quarter. But after the final turnover, history will sadly no longer remember Game 3 as the Ian Clark Game.</p>

    <h3>1. Harden was just great enough for the Rockets</h3>

    <p>James Harden's first two games went poorly by his standards, shooting a combined 14-of-38 with 11 turnovers. On Thursday, he got back to his roots, attempting 11 free throws and coming damn close to a triple double with eight rebounds and nine assists. This dunk was a good summation of his evening, not to mention the game-winning shot.</p>

    <h3>2. Mid-range jumpers carried the gunslinging Warriors</h3>

    <p>It's fun seeing teams play atypical to everything we know and love about them, and Golden State's second half push to get back into the game led by Shaun Livingston's mid-range game was just a delight. Livingston has one of the strangest skill sets in the NBA, but he's an absolutely perfect fit for the Warriors, playing the yang to Stephen Curry's shooting yin. Elevated into the starting lineup in Curry's absence, Livingston pushed Golden State by relying on what he knows best: funky jumpers from about 15 feet out, both pulling up and out of the post.</p>

    <p>We're so used to seeing everything the Warriors do come from behind the three-point line thanks to Curry. Watching them gun from shorter distances was strange in a great way.</p>

    <h3>3. This series is getting heated</h3>

    <p>Almost every playoff series does by Game 3 or 4. When two teams play each other with high stakes for several days in a row, it's hard not to. On Thursday, it might have started with this blatantly dirty play from Andrew Bogut, which only caused Howard to retaliate with bumps and fouls as often as possible. Bogut didn't back down, either.</p>


The two teams never did anything to draw technical or flagrant fouls, but there was clearly increased physicality on both sides. We'll see if it leads to anything further before the series is up.
  </div>
</div>

app/views/contact/elections.html.erb
<%= render 'shared/content' %>

app/views/contact/index.html.erb
<% ab_test("contact_us", "long", "short") do |summary_test| %>
  <div class="row">
    <div class="span1"></div>
    <h3 class="span8">PLEASE USE THE FORM BELOW TO SEND US YOUR INQUIRY.</h3>
    <div class="span2"></div>

  </div>
  <form class="form-horizontal" role="form" action="/contact" method="post">
    <div class="control-group">
      <label class="control-label" for="required fields"></label>
      <div class="controls">
       <small>Note: All fields are required.</small>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="department">Department:</label>
      <div class="controls">
        <select name="department" id="ndepartment" class="form-control span6 dropdown-department" required>
          <option value="" selected="" style="">Please select a department</option>
          <option value="Ad Operations" style="">Ad Operations</option>
          <option value="For Corrections and Clarifications" style="">For Corrections and Clarifications</option>
          <option value="Newsroom" style="">Newsroom</option>
          <option value="Opinion Submissions" style="">Opinion Submissions</option>
          <option value="Reader Feedback/Letters" style="">Reader Feedback/Letters</option>
          <option value="Press Inquires for Gannett" style="">Press Inquires for Gannett</option>
          <option value="Press Inquiries for USA TODAY" style="">Press Inquiries for USA TODAY</option>
        </select>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="name">Name:</label>
      <div class="controls">
        <input type="text" class="form-control span6" id="name" placeholder="Enter your name" required>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="title">Title:</label>
      <div class="controls">
        <input type="text" class="form-control span6" id="title" placeholder="Enter your title" required>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="email">Email:</label>
      <div class="controls">
        <input type="email" class="form-control span6" id="email" placeholder="Enter your email" required>
      </div>
    </div>
    <% if summary_test == "long" %>
    <div class="control-group">
      <label class="control-label" for="company">Company:</label>
      <div class="controls">
        <input type="text" class="form-control span6" id="company" placeholder="Enter your company" required>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="phone">Phone:</label>
      <div class="controls">
        <input type="tel" class="form-control span6" id="tel" placeholder="Enter your phone number" required>
      </div>
    </div>
    <% end %>
    <div class="control-group">
      <label class="control-label" for="subject">Subject:</label>
      <div class="controls">
        <input type="text" class="form-control span6" id="tel" placeholder="Enter the subject" required>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="subject">Message:</label>
      <div class="controls">
        <textarea rows="7" class="form-control span6" id="tel" placeholder="Enter the Message" required></textarea>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="submit"></label>
      <div class="controls">
        <button type="submit" class="contact-submit btn btn-large btn-primary span5">Submit</button>
      </div>
    </div>
  </form>
<% end %>

app/views/contact/investigations.html.erb
<%= render 'shared/content' %>

app/views/contact/money.html.erb
<%= render 'shared/content' %>

app/views/contact/news.html.erb
<%= render 'shared/content' %>

app/views/contact/opinion.html.erb
<%= render 'shared/content' %>

app/views/contact/sports.html.erb
<%= render 'shared/sports_header' %>
<%= render 'shared/content' %>

app/views/contact/stocks.html.erb
<%= render 'shared/content' %>

app/views/contact/submit.html.erb
<p>
  <h4>Thank You for the feedback.</h4>
</p>

app/views/contact/videos.html.erb
<%= render 'shared/content' %>

app/views/contact/wallstreet.html.erb
<div class="content-description-page">
  <div class="content-description-image">
    <%= image_tag("/assets/sec_wall.jpg") %>
  </div>
  <div class="content-description-content">
    <h4>U.S. stocks close mostly higher, despite hit to tech stocks</h4>
    <p>A rebound in the price of oil and natural gas helped drive sharp gains for energy and financial companies, nudging U.S. stocks mostly higher Friday.</p>
    <p>That offset a slide in the technology sector following disappointing earnings from Microsoft, Google parent Alphabet and other big names.</p>
    <p>The Dow Jones industrial average eked out a tiny gain, while the Standard & Poor's 500 index closed essentially flat. Both ended the week higher. But the tech-heavy Nasdaq composite fell short on both counts.</p>
    <p>“The Nasdaq took a hit today,” said Erik Davidson, chief investment officer at Wells Fargo Private Bank.</p>
    <p>The Dow rose 21.23 points, or 0.1%, to 18,003.75. The S&P 500 index added 0.10 points to 2,091. The Nasdaq composite index lost 39.66 points, or 0.8%, to 4,906.23.</p>

    <p>Trading was listless for much of the day, with the Dow and S&P 500 wavering between small gains and losses as the Nasdaq stayed in the red. As was the case much of the week, investors were focused mostly on company earnings and energy prices.</p>

    <p>The latter helped lift several oil and gas companies.</p>

    <p>Southwestern Energy notched the biggest gain in the S&P 500. The stock vaulted $1.60, or 15%, to $12.27. Range Resources jumped $2.58, or about 7%, to $39.75, while Chesapeake Energy climbed 36 cents, or 5.8%, to $6.55.</p>

    <p>Benchmark U.S. crude rose 55 cents, or 1.3%, to close at $43.73 a barrel in New York. Brent crude, used to price international oils, gained 58 cents, or 1.3%, to close at $45.11 a barrel in London. Natural gas gained 7 cents, or 3.5%, to close at $2.14 per 1,000 cubic feet.</p>

    <p>Investors cheered earnings from Norfolk Southern, which jumped 10.5% after the railroad operator slashed costs during its latest quarter. The stock rose $8.70 to $91.33.</p>

    <p>Quarterly results from several big-name companies failed to impress traders, however.</p>

    <p>American Airlines Group fell 4.5% after the company said weaker fares and labor costs cut into its revenue in the first quarter. The stock shed $1.80 to $38.21.</p>

    <p>Investors sold shares in Starbucks after the coffee chain reported disappointing sales growth for the first three months of the year. The stock lost $2.96, or about 5%, to $57.68.</p>

    <p>Microsoft fell 7.2%, making it the biggest decliner in the S&P 500. The stock lost $4 to $51.78, while Alphabet slid $42.23, or 5.4%, to $737.77. Overall, the technology sector was off about 2%.</p>

    <p>Despite the declines, investors seemed to conclude that the issues driving lackluster results at Alphabet and Microsoft were largely confined to those companies, Davidson said.</p>

    <p>“The broader market is doing better,” he said. “Energy has to be part of that.”</p>

    <p>Bond prices fell. The yield on the 10-year Treasury note rose to 1.89% from 1.86% late Thursday.</p>

    <p>In currency markets, the dollar gained to 111.67 yen from Thursday's 109.53 yen. The euro fell to $1.1245 from $1.1295.</p>
  </div>
</div>

app/views/home/index.html.erb
<%= render 'shared/content' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Usa Today" %></title>
  
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-76771817-1', 'auto');
  ga('send', 'pageview');

  </script>

  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%#= csrf_meta_tags %>

</head>
<body>
  <%= render 'shared/header' %>
  <div class="container" id="main-content">
    <%= yield %>
  </div>
  <%= render 'shared/footer' %>
</body>
</html>

app/views/shared/_carousel_content.html.erb
<div id="myCarousel" class="carousel slide">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item">
      <a href="#"><img src="/assets/bootstrap-01.jpg" /></a>
      <div class="carousel-caption">
        <p>
          Lorem Ipsum is simply dummy text of the printing and typesetting industry.
        </p>
      </div>
    </div>
    <div class="item">
      <a href="#"><img src="/assets/bootstrap-02.jpg" /></a>
      <div class="carousel-caption">
        <p>
          Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.
        </p>
      </div>
    </div>
    <div class="item">
      <a href="#"><img src="/assets/bootstrap-03.jpg" /></a>
      <div class="carousel-caption">
        <p>
          The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested.
        </p>
      </div>
    </div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>

app/views/shared/_content.html.erb
<div class="row-fluid">
  <div class="span12 first-row-content">
    <div class="span8 homepage-main-image">
      <%= render 'shared/carousel_content' %>
    </div>
    <div class="span4">
      <div class="top-stories">
        <%= render 'shared/top_stories' %>
      </div>
    </div>
    <div class="clearfix"></div>
  </div>
</div>
<div class="clearfix"></div>
<div class="row-fluid">
  <div class="span12 second-row-content">
    <%= render 'shared/second_row_content' %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="clearfix"></div>
<div id="footer">
  <div class="container">
    <div class="row-fluid links">
      <div class="footer-container">
        <div class="span12">
          <%= render 'shared/footer/footer_contents' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="header-first-row">
        <%= render 'shared/header_first_row' %>
      </div>
      <div class="clearfix"></div>

        <div class="container nav-collapse">
          <ul class="nav navbar-nav navbar-right span12">
            <%= nav_link 'NEWS', news_path %>
            <%= nav_link 'SPORTS', sports_path %>
            <%= nav_link 'MONEY', money_path %>
            <%= nav_link 'TECH', tech_path %>
            <%= nav_link 'OPINION', opinion_path %>
            <%= nav_link 'VIDEOS', videos_path %>
            <%= nav_link 'STOCKS', stocks_path %>
            <%= nav_link 'ELECTIONS 2016', elections_path %>
            <%= nav_link 'INVESTIGATIONS', investigations_path %>
            <%= nav_link 'CONTACT US', contact_path %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">More <span class="caret"></span></a>
              <!--<ul class="dropdown-menu">
                <li>
                  <a href="#">test</a>
                  <a href="#">test</a>
                  <a href="#">test</a>
                </li>
              </ul>-->
            </li>
          </ul>
        </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/shared/_header_first_row.html.erb
<div class="row">
  <div class="navbar-logo span6">
    <a class="navbar-brand" href="/"><img src="/assets/logo.png"></a>
  </div>
  <div class="search-section span6">
    <div class="input-append row-fluid">
      <input class="span9" id="appendedInputButton" type="text"/>
      <button type="submit" class="btn btn-primary">
        <i class="icon-search"></i>
      </button>
    </div>
  </div>
  <div class="clearfix"></div>
</div>

app/views/shared/_second_row_content.html.erb
<div class="span3">
  <div class="image-container">
    <a href="/prince">
      <img src="/assets/sec_prince.jpg" />
    </a>
  </div>
  <h4>
  <a href="/prince"> Prince</a></h4>
  <div class="sec-content-container">
    <p>MINNEAPOLIS (AP) — An autopsy is scheduled Friday to determine what caused the death of the iconic musician Prince, who was found unresponsive in an elevator by sheriff's deputies at his suburban Minneapolis compound a day earlier.</p>
  </div>
</div>
<div class="span3">
  <div class="image-container">
    <a href="golden-state-warriors">
      <img src="/assets/sec_dubbs.jpg" />
    </a>
  </div>
  <h4><a href="golden-state-warriors">Golden State Warriors</a></h4>
  <div class="sec-content-container">
    <p>For the second-straight game, the Golden State Warriors played the Houston Rockets without Stephen Curry. Somehow, despite several miscues in the final minute, the Rockets barely snuck out a win on their home floor, with their 97-96 victory reducing the series to a 2-1 Warriors lead.</p>
  </div>
</div>
<div class="span3">
  <div class="image-container">
    <a href="caterpillar">
      <img src="/assets/sec_caterpillar.jpg" />
    </a>
  </div>
  <h4><a href="caterpillar">Caterpillar</a></h4>
  <div class="sec-content-container">
    <p>(Reuters) - Caterpillar Inc. (CAT.N) lowered its 2016 sales and earnings outlook and posted a lower first-quarter net profit on Friday as revenues declined in the company's construction, oil and gas, mining and rail business segments.</p>
  </div>
</div>
<div class="span3">
  <div class="image-container">
    <a href="wallstreet">
      <img src="/assets/sec_wall.jpg" />
    </a>
  </div>
  <h4><a href="wallstreet">Wall Street</a></h4>
  <div class="sec-content-container">
    <p>A rebound in the price of oil and natural gas helped drive sharp gains for energy and financial companies, nudging U.S. stocks mostly higher Friday.
    That offset a slide in the technology sector following disappointing earnings from Microsoft, Google parent Alphabet and other big names.</p>
  </div>
</div>

app/views/shared/_sports_header.html.erb
<div class="navbar navbar-inverse visible-desktop hidden-tablet hidden-phone">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="header-first-row">
        <%#= render 'shared/header_first_row' %>
      </div>
      <div class="clearfix"></div>

        <div class="container nav-collapse">
          <ul class="nav navbar-nav navbar-right span12">
            <li class="active"><a href="#">NFL</a></li>
            <li class=""><a href="#">MLB</a></li>
            <li class=""><a href="#">NBA</a></li>
            <li class=""><a href="#">NHL</a></li>
            <li class=""><a href="#">NCAAF</a></li>
            <li class=""><a href="#">NCAAB</a></li>
            <li class=""><a href="#">GOLF</a></li>
            <li class=""><a href="#">NASCAR</a></li>
            <li class=""><a href="#">INDYCAR</a></li>
            <li class=""><a href="#">UFC</a></li>
            <li class=""><a href="#">FANTASY</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">More <span class="caret"></span></a>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/shared/_top_stories.html.erb
<h4>TOP STORIES</h4>
<table class="table table-hover">
  <tr>
    <td>
      <a href="http://www.usatoday.com/story/news/politics/onpolitics/2016/04/19/what-time-do-polls-close-in-new-york/83191086/" target="_blank">
        N.Y. primary: What we'll know and when
      </a>
    </td>
  </tr>
  <tr>
    <td>
      <a href="http://www.usatoday.com/story/sports/nfl/2016/04/19/johnny-manziel-agent-drew-rosenhaus/83251816/" target="_blank">
        Manziel: I hope to 'take care of the issues'
      </a>
    </td>
  </tr>
  <tr>
    <td>
      <a href="http://www.usatoday.com/story/news/nation-now/2016/04/19/jared-fogle-child-pornography-sentence-appeal/83239518/" target="_blank">
        Fogle texts show him seeking sex with victims
      </a>
    </td>
  </tr>
  <tr>
    <td>
      <a href="http://www.usatoday.com/story/tech/2016/04/19/intel-layoffs-12000-11/83242832/" target="_blank">
        Intel to lay off 11% of workforce
      </a>
    </td>
  </tr>
  <tr>
    <td>
      <a href="http://www.usatoday.com/story/news/politics/onpolitics/2016/04/19/rep-peter-king-says-ll-take-cyanide-if-ted-cruz-wins-gop-nomination/83240336/" target="_blank">Rep. King taking 'cyanide' if Cruz wins nomination
      </a>
    </td>
  </tr>
  <tr>
    <td>
      <a href="http://www.usatoday.com/story/tech/2016/04/19/amazon-offers-one-day-sale-echo/83224644/" target="_blank">
        Amazon offers one-day sale on Echo
      </a>
    </td>
  </tr>
  <tr>
    <td>
      <a href="http://usatodayhss.com/2016/14-year-old-nevada-youth-football-player-dies-after-collapsing-on-field" target="_blank">
        Youth football player dies after collapsing 
      </a>
    </td>
  </tr>
  <tr>
    <td>
      <a href="http://www.usatoday.com/story/money/2016/04/19/coal-industry-energy-fallout/82972958/" target="_blank">
        How coal's demise threatens Appalachia
      </a>
    </td>
  </tr>
  <tr>
    <td>
      <a href="http://www.usatoday.com/story/news/nation-now/2016/04/19/bizarre-mcdonalds-order-hoax/83241238/" target="_blank">
        McDonald's milkshake saga too good to be true
      </a>
    </td>
  </tr>
  <tr>
    <td>
      <a href="http://www.usatoday.com/story/life/people/2016/04/22/prince-last-30-days/83409562/" target="_blank">
        Inside the last month of Prince's life
      </a>
    </td>
  </tr>
</table>

app/views/shared/footer/_footer_information_links.html.erb
<ul>
  <li><a href="#">About Us</a></li>
  <li><a href="#">Editorial Policy</a></li>
  <li><a href="#">Jobs</a></li>
  <li><a href="#">Internships</a></li>
</ul>

app/views/shared/footer/_footer_life_links.html.erb
<ul>
  <li><a href="#">People</a></li>
  <li><a href="#">Entertain This!</a></li>
  <li><a href="#">Movies</a></li>
  <li><a href="#">Music</a></li>
  <li><a href="#">TV</a></li>
  <li><a href="#">Books</a></li>
</ul>

app/views/shared/footer/_footer_money_links.html.erb
<ul>
  <li><a href="#">Markets</a></li>
  <li><a href="#">Business</a></li>
  <li><a href="#">Personal Finance</a></li>
  <li><a href="#">Cars</a></li>
</ul>

app/views/shared/footer/_footer_news_links.html.erb
<ul>
  <li><a href="#">Nation</a></li>
  <li><a href="#">World</a></li>
  <li><a href="#">Washington</a></li>
  <li><a href="#">Election 2016</a></li>
</ul>

app/views/shared/footer/_footer_sports_links.html.erb
<ul>
  <li><a href="#">NFL</a></li>
  <li><a href="#">MLB</a></li>
  <li><a href="#">NBA</a></li>
  <li><a href="#">NHL</a></li>
  <li><a href="#">NCAAF</a></li>
  <li><a href="#">NCAAB</a></li>
  <li><a href="#">NCAAW</a></li>
  <li><a href="#">NASCAR</a></li>
  <li><a href="#">Golf</a></li>
  <li><a href="#">Fantasy</a></li>
  <li><a href="#">Soccer</a></li>
  <li><a href="#">UFC</a></li>
</ul>

app/views/shared/footer/_footer_stay_connected_links.html.erb
<ul>
  <li><a href="#">Staff Index</a></li>
  <li><a href="#">Get Home Delivery</a></li>
</ul>

app/views/shared/footer/_footer_tech_links.html.erb
<ul>
  <li><a href="#">News</a></li>
  <li><a href="#">Reviews</a></li>
  <li><a href="#">Columnists</a></li>
  <li><a href="#">Gaming</a></li>
</ul>

app/views/shared/footer/_footer_travel_links.html.erb
<ul>
  <li><a href="#">Business Travel</a></li>
  <li><a href="#">Experience Travel</a></li>
  <li><a href="#">Destinations</a></li>
  <li><a href="#">Flights</a></li>
</ul>